### ISSUE TITLE
Add bonuses

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#10]
Add a service that makes three bonuses per day which will be multipliers for categories or types of items like indoor items, food, plants ext. Give the three of them an increasing multiplier of 1.25x 2x 4x respectively.

**Comment by Ekwav** [comment]
3 categories should get a random bonus of 25% 2x or 4x randomly a day?

**Comment by tentamens** [comment]
> 3 categories should get a random bonus of 25% 2x or 4x randomly a day?

Right now I have it at 1.25x 2x and 4x, we can change these around in the future.
Also I have a feeling you would ask this but I don't think words should be reserved for some multipliers so household items could be 1.25x 2x 4x ext.

**Comment by Ekwav** [comment]
I still don't  quite understand.
So I suppose 3 categories would be chosen at random? One for each multiplier. 
And then add extra exp if a image from that category gets uploaded. 
How would that look like in the UI. How do you find out what has which multiplier?

**Comment by Ekwav** [comment]
for the record 
![image](https://github.com/Coflnet/CtwApi/assets/16632490/c85293e5-8806-4282-870a-7322b139ab68)
