### ISSUE TITLE
new Challenge/quest

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#12]
( Maybe make a whole system for quests/Challenges so they can be easily added or changed)
A quest for every 5 "new" items (be in the first say 50 to collect the item) you gain 5,000 XP

**Comment by Ekwav** [comment]
You want a daily quest to collect 5 items that have never been collected before?

**Comment by tentamens** [comment]
No this wouldn't be daily. There would be no time limit.
Can you also make a API for the newest items sorted by newest and time ( for each level like 450XP/350XP ext. the old will be at the bottom)

**Comment by Ekwav** [comment]
> No this wouldn't be daily. There would be no time limit. Can you also make a API for the newest items sorted by newest and time ( for each level like 450XP/350XP ext. the old will be at the bottom)

So more like achievements of reaching a milestone?
You could sort by exp yourself or create a separate issue for that

**Comment by tentamens** [comment]
needed
