### ISSUE TITLE
Stats endpoint returns 404

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#15]
when requesting /stats endpoint it returns 404 from Nginx? this may be a Flou issue.
I also made sure this wasn't an issue with the generated code in Flutter, by calling it in [API doc](https://ctw.coflnet.com/api/index.html). Which may mean it's just an issue with open-API

**Comment by Ekwav** [comment]
Solved by moving the stats to the prefix `/api` in #14
