### ISSUE TITLE
Stats to add

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#17]
Add top ten finishes (daily or weekly) and unique images taken.

**Comment by tentamens** [comment]
also their daily streak

**Comment by tentamens** [comment]
needed

**Comment by Ekwav** [comment]
Why is this needed for the MVP?

**Comment by tentamens** [comment]
Yes it is needed The stats I need 
All time leaderboard position, total pictures taken, "new" pictures taken, top ten placements, daily top ten total xp
