### ISSUE TITLE
Easy items for new users

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#20]
make the first 10-20 items easy, like a mug hand ext. just so a user doesn't download the app and have to find a very specific item and then delete the game.

**Comment by tentamens** [comment]
also maybe make the first couple of items be household items for that matter

**Comment by Ekwav** [comment]
which should be the first 20?

**Comment by tentamens** [comment]
You first make 20 or so and then we will go through it together

**Comment by tentamens** [comment]
Chair, apple, bed, pillow, folded blanket, lamp, smartphone, pencil, key, key fob, water bottle, water glass, book, earbuds, laptop, toothbrush, toothpaste, shoes, jacket, shirt, pants, flashlight, fork, spoon, knife
