### ISSUE TITLE
Daily items

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#21]
Make an endpoint for daily items. 
The number of items: Start with 15 and maybe adjust that in the future.
XP per item: for every item, give them between 50-250 XP in intervals of 25.
Item Quests: Starting at needing to collect 1 of the items, increasing by 2 each time. Reward the user 75 XP, increasing by 1.5x each time (applying all multipliers)

**Comment by Ekwav** [comment]
isn't that two features?

**Comment by tentamens** [comment]
Yeah, they are both for daily items.

**Comment by tentamens** [comment]
Needed

**Comment by tentamens** [comment]
Give each ITEM a value between 50-250 XP in intervals of 25.
