### ISSUE TITLE
Multiplier API returning null

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#22]
This is the return values:
`MultiplierResponse[success=true, multiplier=[ActiveMultiplier[multiplier=1.25, category=animal], ActiveMultiplier[multiplier=null, category=clothes], ActiveMultiplier[multiplier=null, category=fruit]]]`

**Comment by Ekwav** [comment]
I don't quite understand, that is not null

**Comment by tentamens** [comment]
multiplier=null
