### ISSUE TITLE
Changes to image upload endpoint

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#24]
Return whether it was a "new" item (Be in the first 20 to collect it) 
Also when it actually comes time to process the images have it so that if it takes longer than say 2 seconds to process the image just award the user XP anyway and take it away later if needed.

**Comment by Ekwav** [comment]
I don't quite understand, you can tell by the size of the reward if its a "new" image.
Also The backend can't detect how long it is taking for the image to be uploaded. If you want to show the user something different after two seconds you can.
