### ISSUE TITLE
Leaderboard xp rewards

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#27]
Daily leaderboard give top ten +1000XP give 1,2,3 3000,2000,1000 in their respective order.
For Weekly give top twenty 3000k give 1,2,3 6000,3000,2000 in their respective order.

**Comment by Ekwav** [comment]
I made the reward for weekly (6000,4000 and 2000) + 3000 for the top 3 because giving the 3rd less than the 4th makes no sense to me
