### ISSUE TITLE
Leaderboard issues

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#31]
Daily doesn't have an avatar and no users show up in the weekly leaderboard

**Comment by Ekwav** [comment]
Can't reproduce
weekly leaderboard response:
```
[
  {
    "user": {
      "userId": "847e326b-c39b-484e-9621-c46962d04c04",
      "name": "tentamens ",
      "avatar": "SJiksI"
    },
    "score": 820
  }
]
```

**Comment by tentamens** [comment]
Then it's probably because I am calling it under the wrong name, can I just request "exp_weekly" and you return me the current week. Like how I request all-time. Instead of the current way

**Comment by Ekwav** [comment]
Since I don't expect confusion with another weekly leaderbaord I called it `daily` `weekly` and `overall`  in https://github.com/Coflnet/CtwApi/commit/c913ef010cf8ac3a4663b61cdedbc4bfaa306bf8
