### ISSUE TITLE
Add a new leaderboard endpoint

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#32]
So I don't have to call `api/leaderboard/boardName/me` three time to get the user's position of each board, can you just give me one that returns all three?

**Comment by Ekwav** [comment]
Your absolute position or also the people around you?
Could be used by you to make a fancy you overtook `x` display

**Comment by tentamens** [comment]
No, just your position on the leaderboard like 69 or 16 ext.

And I can already do what you said by requesting the leaderboard at x offset.
