### ISSUE TITLE
Upload image fail 

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#36]
uploading image returns 500 error code

**Comment by tentamens** [comment]
Failed to upload image. Status code: {"slug":"internal_error","message":"An unexpected internal error occured. Please check that your request is valid. If it is please report he error and include reference \u00274f009b25c317ec10fcdf79ec0c4b2a16\u0027.","trace":"ctwapi-59c86b9f7f-94nz5.4f009b25c317ec10fcdf79ec0c4b2a16"}

**Comment by Ekwav** [comment]
DB-overload exception was fixed with a row-level repair
