### ISSUE TITLE
New stats for image upload

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#40]
Add the times the item has been collect in the image upload response

**Comment by tentamens** [comment]
Add the amount of remaining skips to the user in the upload response.

**Comment by tentamens** [comment]
> Add the amount of remaining skips to the user in the upload response.

Make that how much they gain so you don't have to return each time if they maxed out at 2 for example

**Comment by Ekwav** [comment]
Every upload grants a skip, there is no limit. An user only starts out with 2
