### ISSUE TITLE
Issues with image upload

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#41]
This is the response I got when uploading acorn.
`{image: {id: b1598985-5e53-44ea-b22f-c11a77710cb9, userId: 847e326b-c39b-484e-9621-c46962d04c04, objectLabel: apple, description: null, day: 1642, verifications: 0, metadata: null, contentType: image/jpeg, size: 353601}, rewards: {total: 0, multiplier: 0, imageBonus: 490, isCurrent: false, unique: false, dailyItemReward: 0, dailyQuestReward: 0}}`
There's no multiplier and no total, which doesn't make much sense at all. There should be a multiplier from the bonus "forest" it also seems like it did apply one, but I'm not sure

**Comment by Ekwav** [comment]
acorn is (also) in the category `woodsy` thus no forest multiplayer applied
