### ISSUE TITLE
New endpoint

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#42]
Make an endpoint that I call on start up and notifies the user if they had XP removed for added from their account. Example, placing top ten in the leaderboard or got XP removed because they took the wrong image of an item ext.

**Comment by tentamens** [comment]
I will be displaying the content returned so it is customizable as well as having different variations of "popups"
Right now I have reward, penalty, info, legal, and update. You don't have to worry much about these, but you will have to return me a number corresponding to the type of popup.

Now for the actually content it will be rendering, I will need the header, body, and reward, these will all be in the form of text. And once I finish making all these widgets I will write prompts for you

**Comment by tentamens** [comment]
For Rewards, all we have right now are the leaderboard so
For placing (top ten, top twenty, 1st, 2nd, 3rd) in the (daily, weekly) leaderboard you have been awarded 
For uploading an incorrect image, you have deducted
obviously we can add more at any time without any changes to the front-end, so it doesn't really madder that much what they are now

**Comment by tentamens** [comment]
Also we can use this endpoint for changing numbers of the frontend like multipliers or leaderboard rewards. So add support for that aswell

**Comment by Ekwav** [comment]
What format should the response have?
Also, wouldn't you want a list of recent exp changes? Like just requesting the latest one may miss one

**Comment by tentamens** [comment]
The response could just be an array of dictionaries, each dictionary being a "notifier" 
The type of if notifier would be a string reward, penalty, info, legal, and update. Header String, Body string, Reward String
For changes in frontend numbers like rewards you can put a bool and data this is all I have for now
dailyBonusesList = [1.25, 2, 4];
leaderboardBaseRewardsList = [1000, 3000];
leaderboardTopThree = [
  [3000, 2000, 1000],
  [6000, 3000, 2000]
];

**Comment by Ekwav** [comment]
I didn't get your message.  
How about this:
```json
[
  {
    "description":"Finished at #1 on the daily leaderbaord",
    "reference":"2024-07-08",
    "type":"leaderbaord",
    "timestamp": "2024-07-08T0:04:10.329Z",
    "effect":4000
  },
  {
    "description":"Image does not contain a window",
    "reference":"b0d070d6-702b-4242-ab29-f5410b2a2c92",
    "type":"image_check",
    "timestamp": "2024-07-07T23:54:20.032Z",
    "effect":-400
  }
]
```
The type defines what source the change came from.  
Reference is an unique id for the change (boardname for leaderbaord, image id for images) changes based on type.
The effect is by how much the exp changed.
The description is text that can be displayed to the user.
The timestamp states when the change happened. (mostly for ordering)

**Comment by tentamens** [comment]
Yeah, that works

**Comment by tentamens** [comment]
Also for testing can you make it always return all of them

**Comment by tentamens** [comment]
> Also for testing can you make it always return all of them

This

**Comment by Ekwav** [comment]
It does return you all of them. All in the last 30 days (that is how long they are stored)
