### ISSUE TITLE
Couple issues with stats endpoint

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#43]
When I uploaded an image of an item, I have already collected before images_uploaded still increases. Also, I somehow have three skips available, it should be maxed out at 2.

**Comment by tentamens** [comment]
also, is there a reason you have to return me the User-id for each item? Seems kinda wasteful.

**Comment by tentamens** [comment]
It also increase remaining skips when collecting a already collected item

**Comment by tentamens** [comment]
If I have 0 skips remaining, I collect one image I now have 3

**Comment by Ekwav** [comment]
images_uploaded counts how many images you have uploaded, so that is how its supposed to be
