### ISSUE TITLE
Uploading Error

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#44]
When uploading an item I haven't already, I get 500 status code
`Failed to upload image. Status code: {"slug":"internal_error","message":"An unexpected internal error occured. Please check that your request is valid. If it is please report he error and include reference \u00270bd7518990f67ad53b56edaaf82e1706\u0027.","trace":"ctwapi-59c86b9f7f-94nz5.0bd7518990f67ad53b56edaaf82e1706"}
I/flutter (18422): 500`

**Comment by Ekwav** [comment]
Could not reproduce, what image did you try to upload?
