### ISSUE TITLE
500 error when calling skip endpoint

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#45]
Only happened once, couldn't reproduce still an issue tho
`\u00270893d2cfdab59e9c7d84ef1dff83aed2\u0027.","trace":"ctwapi-59c86b9f7f-94nz5.0893d2cfdab59e9c7d84ef1dff83aed2"`

**Comment by tentamens** [comment]
Not sure if this is related but when calling it with 0 skips it also throws 500 I did have skips left in the first one tho

**Comment by tentamens** [comment]
> Not sure if this is related but when calling it with 0 skips it also throws 500 I did have skips left in the first one tho

Well never mind? Called it again, thought I was out of skips, but it works?
Edit I can keep calling forever it seems without getting more skips, very broken

**Comment by Ekwav** [comment]
Could not reproduce, I assume I fixed it as a sideffect of another change

**Comment by tentamens** [comment]
Failed to upload image. Status code: {"slug":"internal_error","message":"An unexpected internal error occured. Please check that your request is valid. If it is please report he error and include reference \u0027a89e2817971ccc96a261e30d7d06b0c4\u0027.","trace":"ctwapi-8bc4fd699-gzw85.a89e2817971ccc96a261e30d7d06b0c4"}
I/flutter (20149): 500
I took a picture of a "pineapple"
