### ISSUE TITLE
Issues with image upload endpoint

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#49]
Rename image bonus to baseReward
Unqiue is false when it should be true
dailyItemReward says 0 even when `challange/daily` says I have 4 progress
collectedTimes should start at 1

**Comment by tentamens** [comment]
Add a param to the response wasCorrect or something like thats false by default but true if the ai said the word wasn't an item

**Comment by Ekwav** [comment]
> Add a param to the response wasCorrect or something like thats false by default but true if the ai said the word wasn't an item

shouldn't that be the other way around? wasCorrect is true if it is an item, so by default except the ai said is not?

**Comment by tentamens** [comment]
> > Add a param to the response wasCorrect or something like thats false by default but true if the ai said the word wasn't an item
> 
> shouldn't that be the other way around? wasCorrect is true if it is an item, so by default except the ai said is not?

Doesn't really madder what the name is. You get the idea

**Comment by tentamens** [comment]
Also, make imageReward always have a value (the images base reward)

**Comment by tentamens** [comment]
Also return the users current skips or just when the increased like for daily streak

**Comment by tentamens** [comment]
When collecting a word in your list "cherry" imageReward was 500 and total was 0?

**Comment by Ekwav** [comment]
* dailyItemReward is `how much reward was added because item is one of daily items`
* `Stats.IsNoItem` tells you that there are no rewards because its probably something that can't be photographed
* BaseReward has now always a value (unless IsNoItem is true)
* `Rewards.AddedSkp` is true if a skip was added

did you try cherry on the same day before?
