### ISSUE TITLE
exp/history changes

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#52]
Gives each item a UID so it's easier to verify whether I have displayed it before.

**Comment by tentamens** [comment]
can you also return change as a string so +500XP, this is so if the user is awarded skips it can be +1 skip ext

**Comment by Ekwav** [comment]
its exp history why would it return skips?

**Comment by tentamens** [comment]
> its exp history why would it return skips?

Because I wanted to the endpoint to alert the user of anything that has happened or changed in the app but you made it exp history
