### ISSUE TITLE
I tried to tell you

### ISSUE THREAD

**Issue by tentamens** [Coflnet/CtwApi#64]
You know, I tried to tell you that 500 xp was to much to start with.. Make collecting an Image start at 250 reduce by 50 at a time. I tried to tell you, but here we are. Also, if you bring this up there will be a 4-hour HR meetings where we do the first 2 hours in the morning and then 2.5 hours later we do the other 2 hours with maybe some more time bleeding over to 5–6 hours total. Also there will be a 2-week sprint

**Comment by Ekwav** [comment]
Looking forward to our meeting
